stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/feature_add.py
    deps:
    - data/processed
    - src/feature_add.py
    outs:
    - data/final

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/final
    - src/model_building.py
    params:
    - model_building.max_iter
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models     # Track entire models folder

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
params:
- dvclive/params.yaml
